// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: account/interface/v1/notice.proto

package interfacev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on NoticeListRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *NoticeListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NoticeListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// NoticeListRequestMultiError, or nil if none found.
func (m *NoticeListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *NoticeListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return NoticeListRequestMultiError(errors)
	}

	return nil
}

// NoticeListRequestMultiError is an error wrapping multiple validation errors
// returned by NoticeListRequest.ValidateAll() if the designated constraints
// aren't met.
type NoticeListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NoticeListRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NoticeListRequestMultiError) AllErrors() []error { return m }

// NoticeListRequestValidationError is the validation error returned by
// NoticeListRequest.Validate if the designated constraints aren't met.
type NoticeListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NoticeListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NoticeListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NoticeListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NoticeListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NoticeListRequestValidationError) ErrorName() string {
	return "NoticeListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e NoticeListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNoticeListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NoticeListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NoticeListRequestValidationError{}

// Validate checks the field values on NoticeListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *NoticeListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NoticeListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// NoticeListResponseMultiError, or nil if none found.
func (m *NoticeListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *NoticeListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, NoticeListResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, NoticeListResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return NoticeListResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return NoticeListResponseMultiError(errors)
	}

	return nil
}

// NoticeListResponseMultiError is an error wrapping multiple validation errors
// returned by NoticeListResponse.ValidateAll() if the designated constraints
// aren't met.
type NoticeListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NoticeListResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NoticeListResponseMultiError) AllErrors() []error { return m }

// NoticeListResponseValidationError is the validation error returned by
// NoticeListResponse.Validate if the designated constraints aren't met.
type NoticeListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NoticeListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NoticeListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NoticeListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NoticeListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NoticeListResponseValidationError) ErrorName() string {
	return "NoticeListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e NoticeListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNoticeListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NoticeListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NoticeListResponseValidationError{}

// Validate checks the field values on Notice with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Notice) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Notice with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in NoticeMultiError, or nil if none found.
func (m *Notice) ValidateAll() error {
	return m.validate(true)
}

func (m *Notice) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Content

	if len(errors) > 0 {
		return NoticeMultiError(errors)
	}

	return nil
}

// NoticeMultiError is an error wrapping multiple validation errors returned by
// Notice.ValidateAll() if the designated constraints aren't met.
type NoticeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NoticeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NoticeMultiError) AllErrors() []error { return m }

// NoticeValidationError is the validation error returned by Notice.Validate if
// the designated constraints aren't met.
type NoticeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NoticeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NoticeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NoticeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NoticeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NoticeValidationError) ErrorName() string { return "NoticeValidationError" }

// Error satisfies the builtin error interface
func (e NoticeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNotice.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NoticeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NoticeValidationError{}
